{{- if .Values.webhook }}
{{- if .Values.webhook.create }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: loft-agent
---
apiVersion: v1
kind: Service
metadata:
  name: loft-agent-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app: {{ template "loft.fullname" . }}
    release: {{ .Release.Name }}
{{- end }}
{{- end }}